#title in header
title: "xu"

#main info
#owner
owner: "Diogo Santiago Antunes"
info: "A student at IST"
#description
desc: "a blog made for me"

#menu
menu:
  About: /about
  Posts: /posts
  Projects: /projects
  "CS and Math": /CS-Math

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Portugal
placelink: https://en.wikipedia.org/wiki/Portugal
github: https://github.com/diogoantunes25
linkedin: https://www.linkedin.com/in/diogo-antunes-025/

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# favicon
# TODO: Change this
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
